apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  template:
    spec:
      volumes:
        - name: env-file
          secret:
            secretName: auth-secret
            items:
              - key: .env
                path: .env
      containers:
        - name: auth-service
          volumeMounts:
            - name: env-file
              mountPath: /app/.env
              subPath: .env
