apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: ghcr.io/nh-homelab/auth-service:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ghcr-creds
